use_frameworks!
source 'https://github.com/RisingSSR/RisingCyxbsSepc.git'
source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'

platform :ios, '11.0'

target 'RyCyxbsThirdEX_Example' do
  pod 'RyCyxbsThirdEX', :path => '../'

  target 'RyCyxbsThirdEX_Tests' do
    inherit! :search_paths

    
  end
end
